ghibli = Studio.create!(name: "Studio Ghibli", location: "Tokyo")
A24 = Studio.create!(name: "A24", location: "New York City")
universal = Studio.create!(name: "Universal Pictures", location: "Hollywood")
walt_disney = Studio.create!(name: "Walt Disney", location: "Burbank")

mononoke = ghibli.movies.create!(title: "Princess Mononoke", creation_year: 1997, genre: "Action")
spirited_away = ghibli.movies.create!(title: "Spirited Away", creation_year: 2001, genre: "Adventure")
uncut_gems = A24.movies.create!(title: "Uncut Gems", creation_year: 2019, genre: "Crime/Thriller")
talk_to_me = A24.movies.create!(title: "Talk To Me", creation_year: 2022, genre: "Supernatural/Horror")
jurassic = universal.movies.create!(title: "Jurassic World", creation_year: 2015, genre: "Science Fiction")
ex_machina = universal.movies.create!(title: "Ex-Machina", creation_year: 2014, genre: "Science Fiction/Psychological Thriller")
ralph = walt_disney.movies.create!(title: "Wreck It Ralph", creation_year: 2012, genre: "Comedy")
frozen = walt_disney.movies.create!(title: "Frozen", creation_year: 2013, genre: "Musical Fantasy")

#id of this dude is 1
new_actor = Actor.create!(name: "Joseph Lee", age: 26)
#id of this actress is 2
new_actress = Actor.create!(name: "Taylor Swift", age: 28)


mononoke_actor = mononoke.actors.create!(name: "John DiMaggio", age: 45)
mononoke_actress = mononoke.actors.create!(name: "Claire Danes", age: 37)
spirited_away_actor = spirited_away.actors.create!(name: "Jason Marsden", age: 40)
spirited_away_actress = spirited_away.actors.create!(name: "Rumi Hiiragi", age: 30)
uncut_gems_actor = uncut_gems.actors.create!(name: "Adam Sandler", age: 51)
uncut_gems_actress = uncut_gems.actors.create!(name: "Julia Fox", age: 39)
talk_to_me_actor = talk_to_me.actors.create!(name: "Zoe Terakes", age: 28)
talk_to_me_actress = talk_to_me.actors.create!(name: "Sophie Wilde", age: 26)
jurassic_actor = jurassic.actors.create!(name: "Chris Pratt", age: 45)
jurassic_actress = jurassic.actors.create!(name: "Isabella Sermon", age: 15)
ex_machina_actor = ex_machina.actors.create!(name: "Oscar Issace", age: 55)
ex_machina_actress = ex_machina.actors.create!(name: "Alicia Vikander", age: 41)
ralph_actor = ralph.actors.create!(name: "Rich Moore", age: 42)
ralph_actress = ralph.actors.create!(name: "Sarah Silverman", age: 38)
frozen_actor = frozen.actors.create!(name: "Josh Gad", age: 32)
frozen_actress = frozen.actors.create!(name: "Kristen Bell", age: 32)
